### ISSUE TITLE
findEntities method issue with shorthand qualified name of Entity

### ISSUE THREAD

**Issue by Tomac1** [inlm/schema-generator#5]
There is a problem with finding entities from version 0.10.1 when using shortened import instead of fully qualified name in entity.

Cannot use `class Account extends Entity` with  `use \LeanMapper\Entity` at the beginning of the class.
I need to always type `class Account extends \LeanMapper\Entity`. 

It will be fine to find entities with "instance of" if possible.

**Comment by janpecha** [comment]
Fixed, thanks for report.
