### ISSUE TITLE
Acceptance of m:default() annotation

### ISSUE THREAD

**Issue by Tomac1** [inlm/schema-generator#6]
I am trying to generate schema with DEFAULT value. 
It looks default value is not accepted at all.

Example of Entity definition:

```
namespace Model\Entity;

/**
 * @property-read int $id m:schemaPrimary
 * @property string $name m:schemaType(varchar:127) m:schemaComment(Name in original language)
 * @property string $stateCode m:schemaType(char:2) m:schemaComment(ISO 3166-2 alpha 2)
 * @property string $currency m:schemaType(char:3) m:schemaComment(ISO 4217)
 * @property bool $inSchengen m:default(false) m:schemaComment(Is country in Schengen economic zone?)
 *
 * @schemaUnique stateCode
*/
class Country extends BaseEntity {

	const STATE_CODE_CZ = 'CZ';
	const STATE_CODE_SK = 'SK';
	const STATE_CODE_DE = 'DE';

}
```
I am successfully combine ILNM schema generator with Nextras Migrations and it works fine. But when I check structures directory with sql there are any DEFAULTs.

Is it possible to implement default annotation from lean mapper?

**Comment by janpecha** [comment]
Hello, I thought about it but I'm not sure if it is good idea. Because `m:default` is default value for uninitialized (detached) entity and default value of database column is different thing.

Why you need DEFAULT in SQL schema? Maybe can be solution implement new flag `m:schemaDefault(default value)`.

**Comment by Tomac1** [comment]
Hmm, You are right. 
I agree with your solution to implement new flag `m:schemaDefault(default value)`. 
This will solve many things in my model ;-)

**Comment by janpecha** [comment]
New flag `m:schemaDefault` is implemented in newest version. Can you try if is all ok? Thanks :)

**Comment by Tomac1** [comment]
It works nice ;-) Thank you.
