### ISSUE TITLE
Cannot generate schema with more inheritances of entities

### ISSUE THREAD

**Issue by Tomac1** [inlm/schema-generator#8]
Hi John, trying to solve problem with too many inheritances of entities.

I have multiple entities:
- ProductEntity extends BaseEntity
- BaseEntity extends System\BaseEntity 
- System\BaseEntity extends LeanMapper\Entity

I am unable to genereate schema with this path. The only one way to generate schema is remove System\BaseEntity and extend BaseEntity directly by LeanMapper\Entity.

Hope you understand the issue.

**Comment by Tomac1** [comment]
Sorry, it looks that the problem depend on symlinked package.
`System\BaseEntity` is located out of project files and it is loaded as symlink.

**Comment by janpecha** [comment]
Hello. Is symlinked package in paths for `LeanMapperExtractor` (parameter `$directories`)? I tried it and it found entities in symlinked directories/files.

**Comment by Tomac1** [comment]
Hello, I included only the project directory where are only entities which inherit from symlinked package entities.
I need to try some ways again. Meybe I am missing something. I will inform you.

**Comment by Tomac1** [comment]
You are right. There must be also _vendor/package/entity_ directory added into `LeanMapperExtractor `and `$directories` variable. 
Directory must be added also if containes only abstract entities. Now it wortks fine. 
Thank you.
